#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoruBankası.models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HCK")]
	public partial class DBsoruBankasiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSinavBilgileri(SinavBilgileri instance);
    partial void UpdateSinavBilgileri(SinavBilgileri instance);
    partial void DeleteSinavBilgileri(SinavBilgileri instance);
    partial void InsertSinav(Sinav instance);
    partial void UpdateSinav(Sinav instance);
    partial void DeleteSinav(Sinav instance);
    partial void InsertSorular(Sorular instance);
    partial void UpdateSorular(Sorular instance);
    partial void DeleteSorular(Sorular instance);
    #endregion
		
		public DBsoruBankasiDataContext() : 
				base(global::SoruBankası.Properties.Settings.Default.HCKConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBsoruBankasiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBsoruBankasiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBsoruBankasiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBsoruBankasiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SinavBilgileri> SinavBilgileris
		{
			get
			{
				return this.GetTable<SinavBilgileri>();
			}
		}
		
		public System.Data.Linq.Table<Sinav> Sinavs
		{
			get
			{
				return this.GetTable<Sinav>();
			}
		}
		
		public System.Data.Linq.Table<Sorular> Sorulars
		{
			get
			{
				return this.GetTable<Sorular>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinavBilgileri")]
	public partial class SinavBilgileri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _SinavAdi;
		
		private string _Derslik;
		
		private string _GozetmenAdi;
		
		private System.Nullable<int> _SoruSayisi;
		
		private string _Kategori;
		
		private string _ZorlukDerecesi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnSinavAdiChanging(string value);
    partial void OnSinavAdiChanged();
    partial void OnDerslikChanging(string value);
    partial void OnDerslikChanged();
    partial void OnGozetmenAdiChanging(string value);
    partial void OnGozetmenAdiChanged();
    partial void OnSoruSayisiChanging(System.Nullable<int> value);
    partial void OnSoruSayisiChanged();
    partial void OnKategoriChanging(string value);
    partial void OnKategoriChanged();
    partial void OnZorlukDerecesiChanging(string value);
    partial void OnZorlukDerecesiChanged();
    #endregion
		
		public SinavBilgileri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SinavAdi", DbType="NVarChar(50)")]
		public string SinavAdi
		{
			get
			{
				return this._SinavAdi;
			}
			set
			{
				if ((this._SinavAdi != value))
				{
					this.OnSinavAdiChanging(value);
					this.SendPropertyChanging();
					this._SinavAdi = value;
					this.SendPropertyChanged("SinavAdi");
					this.OnSinavAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Derslik", DbType="NVarChar(50)")]
		public string Derslik
		{
			get
			{
				return this._Derslik;
			}
			set
			{
				if ((this._Derslik != value))
				{
					this.OnDerslikChanging(value);
					this.SendPropertyChanging();
					this._Derslik = value;
					this.SendPropertyChanged("Derslik");
					this.OnDerslikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GozetmenAdi", DbType="NVarChar(50)")]
		public string GozetmenAdi
		{
			get
			{
				return this._GozetmenAdi;
			}
			set
			{
				if ((this._GozetmenAdi != value))
				{
					this.OnGozetmenAdiChanging(value);
					this.SendPropertyChanging();
					this._GozetmenAdi = value;
					this.SendPropertyChanged("GozetmenAdi");
					this.OnGozetmenAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoruSayisi", DbType="Int")]
		public System.Nullable<int> SoruSayisi
		{
			get
			{
				return this._SoruSayisi;
			}
			set
			{
				if ((this._SoruSayisi != value))
				{
					this.OnSoruSayisiChanging(value);
					this.SendPropertyChanging();
					this._SoruSayisi = value;
					this.SendPropertyChanged("SoruSayisi");
					this.OnSoruSayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kategori", DbType="NVarChar(50)")]
		public string Kategori
		{
			get
			{
				return this._Kategori;
			}
			set
			{
				if ((this._Kategori != value))
				{
					this.OnKategoriChanging(value);
					this.SendPropertyChanging();
					this._Kategori = value;
					this.SendPropertyChanged("Kategori");
					this.OnKategoriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZorlukDerecesi", DbType="NVarChar(50)")]
		public string ZorlukDerecesi
		{
			get
			{
				return this._ZorlukDerecesi;
			}
			set
			{
				if ((this._ZorlukDerecesi != value))
				{
					this.OnZorlukDerecesiChanging(value);
					this.SendPropertyChanging();
					this._ZorlukDerecesi = value;
					this.SendPropertyChanged("ZorlukDerecesi");
					this.OnZorlukDerecesiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sinav")]
	public partial class Sinav : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _SinavBilgileriId;
		
		private System.Nullable<int> _SoruId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnSinavBilgileriIdChanging(System.Nullable<int> value);
    partial void OnSinavBilgileriIdChanged();
    partial void OnSoruIdChanging(System.Nullable<int> value);
    partial void OnSoruIdChanged();
    #endregion
		
		public Sinav()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SinavBilgileriId", DbType="Int")]
		public System.Nullable<int> SinavBilgileriId
		{
			get
			{
				return this._SinavBilgileriId;
			}
			set
			{
				if ((this._SinavBilgileriId != value))
				{
					this.OnSinavBilgileriIdChanging(value);
					this.SendPropertyChanging();
					this._SinavBilgileriId = value;
					this.SendPropertyChanged("SinavBilgileriId");
					this.OnSinavBilgileriIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoruId", DbType="Int")]
		public System.Nullable<int> SoruId
		{
			get
			{
				return this._SoruId;
			}
			set
			{
				if ((this._SoruId != value))
				{
					this.OnSoruIdChanging(value);
					this.SendPropertyChanging();
					this._SoruId = value;
					this.SendPropertyChanged("SoruId");
					this.OnSoruIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sorular")]
	public partial class Sorular : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _soruid;
		
		private string _soruTipi;
		
		private string _zorlukDerecesi;
		
		private string _kategori;
		
		private string _soruMetni;
		
		private string _soruCevabi;
		
		private string _aSikki;
		
		private string _bSikki;
		
		private string _cSikki;
		
		private string _dSikki;
		
		private System.Nullable<int> _soruPuani;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsoruidChanging(int value);
    partial void OnsoruidChanged();
    partial void OnsoruTipiChanging(string value);
    partial void OnsoruTipiChanged();
    partial void OnzorlukDerecesiChanging(string value);
    partial void OnzorlukDerecesiChanged();
    partial void OnkategoriChanging(string value);
    partial void OnkategoriChanged();
    partial void OnsoruMetniChanging(string value);
    partial void OnsoruMetniChanged();
    partial void OnsoruCevabiChanging(string value);
    partial void OnsoruCevabiChanged();
    partial void OnaSikkiChanging(string value);
    partial void OnaSikkiChanged();
    partial void OnbSikkiChanging(string value);
    partial void OnbSikkiChanged();
    partial void OncSikkiChanging(string value);
    partial void OncSikkiChanged();
    partial void OndSikkiChanging(string value);
    partial void OndSikkiChanged();
    partial void OnsoruPuaniChanging(System.Nullable<int> value);
    partial void OnsoruPuaniChanged();
    #endregion
		
		public Sorular()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soruid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int soruid
		{
			get
			{
				return this._soruid;
			}
			set
			{
				if ((this._soruid != value))
				{
					this.OnsoruidChanging(value);
					this.SendPropertyChanging();
					this._soruid = value;
					this.SendPropertyChanged("soruid");
					this.OnsoruidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soruTipi", DbType="NVarChar(50)")]
		public string soruTipi
		{
			get
			{
				return this._soruTipi;
			}
			set
			{
				if ((this._soruTipi != value))
				{
					this.OnsoruTipiChanging(value);
					this.SendPropertyChanging();
					this._soruTipi = value;
					this.SendPropertyChanged("soruTipi");
					this.OnsoruTipiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zorlukDerecesi", DbType="NVarChar(50)")]
		public string zorlukDerecesi
		{
			get
			{
				return this._zorlukDerecesi;
			}
			set
			{
				if ((this._zorlukDerecesi != value))
				{
					this.OnzorlukDerecesiChanging(value);
					this.SendPropertyChanging();
					this._zorlukDerecesi = value;
					this.SendPropertyChanged("zorlukDerecesi");
					this.OnzorlukDerecesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategori", DbType="NVarChar(50)")]
		public string kategori
		{
			get
			{
				return this._kategori;
			}
			set
			{
				if ((this._kategori != value))
				{
					this.OnkategoriChanging(value);
					this.SendPropertyChanging();
					this._kategori = value;
					this.SendPropertyChanged("kategori");
					this.OnkategoriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soruMetni", DbType="NVarChar(200)")]
		public string soruMetni
		{
			get
			{
				return this._soruMetni;
			}
			set
			{
				if ((this._soruMetni != value))
				{
					this.OnsoruMetniChanging(value);
					this.SendPropertyChanging();
					this._soruMetni = value;
					this.SendPropertyChanged("soruMetni");
					this.OnsoruMetniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soruCevabi", DbType="NVarChar(100)")]
		public string soruCevabi
		{
			get
			{
				return this._soruCevabi;
			}
			set
			{
				if ((this._soruCevabi != value))
				{
					this.OnsoruCevabiChanging(value);
					this.SendPropertyChanging();
					this._soruCevabi = value;
					this.SendPropertyChanged("soruCevabi");
					this.OnsoruCevabiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aSikki", DbType="NVarChar(100)")]
		public string aSikki
		{
			get
			{
				return this._aSikki;
			}
			set
			{
				if ((this._aSikki != value))
				{
					this.OnaSikkiChanging(value);
					this.SendPropertyChanging();
					this._aSikki = value;
					this.SendPropertyChanged("aSikki");
					this.OnaSikkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bSikki", DbType="NVarChar(100)")]
		public string bSikki
		{
			get
			{
				return this._bSikki;
			}
			set
			{
				if ((this._bSikki != value))
				{
					this.OnbSikkiChanging(value);
					this.SendPropertyChanging();
					this._bSikki = value;
					this.SendPropertyChanged("bSikki");
					this.OnbSikkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cSikki", DbType="NVarChar(100)")]
		public string cSikki
		{
			get
			{
				return this._cSikki;
			}
			set
			{
				if ((this._cSikki != value))
				{
					this.OncSikkiChanging(value);
					this.SendPropertyChanging();
					this._cSikki = value;
					this.SendPropertyChanged("cSikki");
					this.OncSikkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dSikki", DbType="NVarChar(100)")]
		public string dSikki
		{
			get
			{
				return this._dSikki;
			}
			set
			{
				if ((this._dSikki != value))
				{
					this.OndSikkiChanging(value);
					this.SendPropertyChanging();
					this._dSikki = value;
					this.SendPropertyChanged("dSikki");
					this.OndSikkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soruPuani", DbType="Int")]
		public System.Nullable<int> soruPuani
		{
			get
			{
				return this._soruPuani;
			}
			set
			{
				if ((this._soruPuani != value))
				{
					this.OnsoruPuaniChanging(value);
					this.SendPropertyChanging();
					this._soruPuani = value;
					this.SendPropertyChanged("soruPuani");
					this.OnsoruPuaniChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
